version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=api_go_std
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  server:
    image: api-go-std:latest
    build: ./
    ports:
      - 8081:8081
    depends_on:
      - postgres
volumes:
  postgres: